---
- name: Установка Nginx
  apt:
    name: "nginx"
    state: present

- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  notify: "Nginx Reloader"

- name: Создание прокси
  ansible.builtin.template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  when: "'vm_1' in inventory_hostname"
  notify: "Nginx Reloader"
